/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaySoloRouteImport } from './routes/play.solo'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as RoomCreateRouteImport } from './routes/room.create'
import { Route as RoomJoinRouteImport } from './routes/room.join'
import { Route as TableDemoRouteImport } from './routes/table.demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySoloRoute = PlaySoloRouteImport.update({
  id: '/play/solo',
  path: '/play/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCreateRoute = RoomCreateRouteImport.update({
  id: '/room/create',
  path: '/room/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomJoinRoute = RoomJoinRouteImport.update({
  id: '/room/join',
  path: '/room/join',
  getParentRoute: () => rootRouteImport,
} as any)
const TableDemoRoute = TableDemoRouteImport.update({
  id: '/table/demo',
  path: '/table/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/solo': typeof PlaySoloRoute
  '/room/$code': typeof RoomCodeRoute
  '/room/create': typeof RoomCreateRoute
  '/room/join': typeof RoomJoinRoute
  '/table/demo': typeof TableDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/solo': typeof PlaySoloRoute
  '/room/$code': typeof RoomCodeRoute
  '/room/create': typeof RoomCreateRoute
  '/room/join': typeof RoomJoinRoute
  '/table/demo': typeof TableDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/solo': typeof PlaySoloRoute
  '/room/$code': typeof RoomCodeRoute
  '/room/create': typeof RoomCreateRoute
  '/room/join': typeof RoomJoinRoute
  '/table/demo': typeof TableDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play/solo'
    | '/room/$code'
    | '/room/create'
    | '/room/join'
    | '/table/demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/play/solo'
    | '/room/$code'
    | '/room/create'
    | '/room/join'
    | '/table/demo'
  id:
    | '__root__'
    | '/'
    | '/play/solo'
    | '/room/$code'
    | '/room/create'
    | '/room/join'
    | '/table/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaySoloRoute: typeof PlaySoloRoute
  RoomCodeRoute: typeof RoomCodeRoute
  RoomCreateRoute: typeof RoomCreateRoute
  RoomJoinRoute: typeof RoomJoinRoute
  TableDemoRoute: typeof TableDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/solo': {
      id: '/play/solo'
      path: '/play/solo'
      fullPath: '/play/solo'
      preLoaderRoute: typeof PlaySoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/create': {
      id: '/room/create'
      path: '/room/create'
      fullPath: '/room/create'
      preLoaderRoute: typeof RoomCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/join': {
      id: '/room/join'
      path: '/room/join'
      fullPath: '/room/join'
      preLoaderRoute: typeof RoomJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/demo': {
      id: '/table/demo'
      path: '/table/demo'
      fullPath: '/table/demo'
      preLoaderRoute: typeof TableDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaySoloRoute: PlaySoloRoute,
  RoomCodeRoute: RoomCodeRoute,
  RoomCreateRoute: RoomCreateRoute,
  RoomJoinRoute: RoomJoinRoute,
  TableDemoRoute: TableDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
